# Configuração do GitHub Pages para LED Telecom Design System
# Este arquivo é usado pelo GitHub Pages para configurar o deploy

# Configurações específicas para o repositório led-telecom/design-tokens
repository: led-telecom/design-tokens
branch: gh-pages
path: storybook-static

# URL final do Storybook
url: https://led-telecom.github.io/design-tokens

# Configurações de build
build_command: npm run build-storybook
output_directory: storybook-static

# Configurações de cache
cache_directories:
  - node_modules
  - .storybook-static
