blank_issues_enabled: false
contact_links:
  - name: LED Telecom Community Support
    url: https://github.com/led-telecom/design-tokens/discussions
    about: Please ask and answer questions here.
  - name: LED Telecom Documentation
    url: https://github.com/led-telecom/design-tokens/wiki
    about: Check our documentation for detailed information.
